(function(){
  const cfg=Object.assign({apiUrl:"/api/chat",title:"RainfallNepal Assistant",subtitle:"Ask about rainfall & the predictor",greeting:"Hi! How can I help?",placeholder:"Type your question…"},window.CW_CONFIG||{});
  const root=document.createElement('div');root.id='cw-root';root.innerHTML=`<div id="cw-panel" role="dialog" aria-label="${cfg.title}" aria-hidden="true"><div id="cw-header"><div class="cw-avatar">☔</div><div><div class="cw-title">${cfg.title}</div><div class="cw-subtitle">${cfg.subtitle}</div></div></div><div id="cw-messages" role="log" aria-live="polite"></div><form id="cw-form"><textarea id="cw-input" rows="1" placeholder="${cfg.placeholder}" aria-label="Message"></textarea><button id="cw-send" type="submit" aria-label="Send"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 2 11 13"/><path d="m22 2-7 20-4-9-9-4Z"/></svg></button></form></div><button id="cw-toggle" aria-expanded="false" aria-label="Open chat"><span class="cw-dot"></span><svg class="cw-icon-chat" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 11.5a8 8 0 0 1-8.5 8A8.5 8.5 0 0 1 4 18l-2 1 1-3a8.5 8.5 0 0 1 3.5-11A8.5 8.5 0 0 1 20 11.5Z"/></svg><svg class="cw-icon-close" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="m6 6 12 12M18 6 6 18"/></svg></button>`;document.body.appendChild(root);
  const toggle=root.querySelector('#cw-toggle'),panel=root.querySelector('#cw-panel'),messages=root.querySelector('#cw-messages'),form=root.querySelector('#cw-form'),input=root.querySelector('#cw-input'),send=root.querySelector('#cw-send'),dot=root.querySelector('.cw-dot');let history=[],opened=false,busy=false;
  const bubble=(text,cls)=>{const d=document.createElement('div');d.className='cw-msg '+cls;d.textContent=text;messages.appendChild(d);messages.scrollTop=messages.scrollHeight;};
  const typing=()=>{const d=document.createElement('div');d.id='cw-typing';d.className='cw-typing';d.innerHTML='<i></i><i></i><i></i>';messages.appendChild(d);messages.scrollTop=messages.scrollHeight;};
  toggle.addEventListener('click',()=>{const open=!root.classList.contains('cw-open');root.classList.toggle('cw-open',open);toggle.setAttribute('aria-expanded',open);panel.setAttribute('aria-hidden',!open);if(open){dot.style.display='none';if(!opened){opened=true;bubble(cfg.greeting,'cw-msg-bot');}input.focus();}});
  form.addEventListener('submit',async e=>{e.preventDefault();const text=input.value.trim();if(!text||busy)return;input.value='';input.style.height='auto';busy=true;send.disabled=true;bubble(text,'cw-msg-user');history.push({role:'user',content:text});typing();try{const r=await fetch(cfg.apiUrl,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text,history})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Chat request failed');document.getElementById('cw-typing')?.remove();const reply=data.reply||data.message||'I could not generate a response.';bubble(reply,'cw-msg-bot');history.push({role:'assistant',content:reply});}catch(err){document.getElementById('cw-typing')?.remove();bubble('The assistant is temporarily unavailable. Please try again in a moment.','cw-msg-error');console.error(err);}finally{busy=false;send.disabled=false;}});
  input.addEventListener('input',()=>{input.style.height='auto';input.style.height=Math.min(input.scrollHeight,96)+'px';});
  input.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();form.requestSubmit();}});
})();
